### ISSUE TITLE
Windows compilation:  dependency on msbuild

### ISSUE THREAD

**Issue by deragon** [twitter/hadoop-lzo#107]
I want to get the library compiled on Windows.  I installed Visual Studio Community, .net Framework 4.5.2 but I fail to put my hands on the 'msbuild' tool; it is simply not there despite having installed these tools.  Thus, compilation fail.

Please document where 'msbuild' can be found or better, remove that dependency.

**Comment by deragon** [comment]
Ok, found 'msbuild'.  Turns out it is actually named 'MSBuild.exe'.   I literately searched for 'msbuild' using Cygwin's `locate` command and it returned nothing since it was case sensitive.  After setting the path correctly, I get the following error:

     [exec] c:\hadoop-lzo\src\main\native\impl\lzo/lzo.h(22): fatal error C1083: Cannot open include file: 'lzo/lzo1.h': No such file or directory [C:\hadoop-lzo\src\main\native\gplcompression.vcxproj]
     [exec]   LzoDecompressor.c
     [exec] c:\hadoop-lzo\src\main\native\impl\lzo/lzo.h(22): fatal error C1083: Cannot open include file: 'lzo/lzo1.h': No such file or directory [C:\hadoop-lzo\src\main\native\gplcompression.vcxproj]

I installed the development package from Cygwin and the files are there...

[WINDOWS machine] dir /usr/include/lzo/lzo1.h
-rw-r--r-- 1 HDerago1 Domain Users 2630 Nov 17  2014 /usr/include/lzo/lzo1.h

...but MSBuild.exe is not aware of Cygwin, of course.  I am a Linux guy, knowing nothing much about Windows except clicking with the mouse.  Can whoever added the support for Windows include instructions on how to build on that platform?

**Comment by sjlee** [comment]
@cnauroth, would you be able to shed some light on @deragon 's issue here? Thanks.

**Comment by cnauroth** [comment]
Hello @sjlee and @deragon .  If the LZO headers can't be found, then that probably means the `C_INCLUDE_PATH` environment variable isn't set.  This is discussed in the "Building and Configuring" section of README.md.

https://github.com/twitter/hadoop-lzo/blob/master/README.md

That file also has some other notes about Windows-specific concerns for the build, including how to build a lzo2.dll for yourself.

My build environment uses Windows SDK 7.1, and builds are issued from the Windows SDK Command Prompt.  I don't know if it's feasible to do a build from within Cygwin.  I didn't have a use case for doing that.

**Comment by deragon** [comment]
Thank you cnauroth.  Unfortunately, I have too many problems under Windows to get anything compiled.  Paths not setup properly, CL.exe crashing ("CL.exe" exited with code -1073741515. ), etc...  I would waste too much time trying to get things running with Microsoft tools.  Instead, I will shuffle my code back and forth between Windows and Linux.

I wish I had the time to investigate all of this, but alas, I must push out code.  Closing this ticket.

**Comment by cnauroth** [comment]
Hi @deragon .  I completely understand that.  If you decide to revisit this at any point and try to put together a patch that adds Cygwin build support, please feel free to notify me again.  I'd be happy to help test and review.
