### ISSUE TITLE
where is /build.properties generated

### ISSUE THREAD

**Issue by cevaris** [twitter/hadoop-lzo#123]
`/build.properties` hadoop-lzo resource file is currently conflicting with our [pants](https://github.com/pantsbuild/pants) build system. 

Any thoughts on where `/build.properties` is generated?

[We see a single use case here](https://github.com/twitter/hadoop-lzo/blob/5e360bdefd8923280b1a0234b845448050bf0caa/src/main/java/com/hadoop/compression/lzo/LzoCodec.java#L100)

**Comment by sjlee** [comment]
The build.properties file is generated by the maven pom (https://github.com/twitter/hadoop-lzo/blob/master/pom.xml#L219). Build.properties has always been there (ivy prior to maven). What kind of issues are you seeing?

**Comment by cevaris** [comment]
pants generates the same `/build.properties` file.
When we import hadoop-lzo, those two `/build.properties` files conflict. Depending on build, we read one vs the other. 

hadoop-lzo seems to be the only library that this is an issue with.

**Comment by sjlee** [comment]
Fixed by #124 .
