### ISSUE TITLE
mvn clean test doesn't build jar

### ISSUE THREAD

**Issue by bryguypgh** [twitter/hadoop-lzo#129]
Am I missing a step? Using a freshly built lzo-2.10, I ran 

C_INCLUDE_PATH=\~/hadooplzo/lzo/include/ LIBRARY_PATH=\~/hadooplzo/lzo/lib/ mvn test

the target directory was created and populated with several directories but no jar file.

$ ls target/
antrun  classes  generated-sources  generated-test-sources  native  surefire-reports  test-classes

**Comment by jrottinghuis** [comment]
I suppose that the docs can be updated to better describe this, but "mvn test" runs the tests but doesn't package any jars. "mvn package" does that.
When I run the following:
$ export C_INCLUDE_PATH=/usr/include/lzo
$ export LIBRARY_PATH=/usr/lib64/
$ export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk/
$ mvn package
...
$ ls target/
antrun   generated-sources               hadoop-lzo-0.4.21-SNAPSHOT-javadoc.jar  maven-archiver    test-classes
apidocs  generated-test-sources          hadoop-lzo-0.4.21-SNAPSHOT-sources.jar  native
classes  hadoop-lzo-0.4.21-SNAPSHOT.jar  javadoc-bundle-options                  surefire-reports

**Comment by bryguypgh** [comment]
Yeah the readme doesn't mention the command "mvn package" at all and if I'm not mistaken mvn package runs the tests anyway so it may be redundant to run them along with the clean?

**Comment by jrottinghuis** [comment]
Created PR to update mvn clean test to mvn clean package, but need to fix build first:
https://github.com/twitter/hadoop-lzo/pull/131

**Comment by jrottinghuis** [comment]
Build 98 failed (https://travis-ci.org/twitter/hadoop-lzo/jobs/287192151). Then the subsequent build worked.
Merged change to comment in readme.
