### ISSUE TITLE
Build Failure on Ubuntu

### ISSUE THREAD

**Issue by giamic** [twitter/hadoop-lzo#135]
Hello,
I follow the build instructions (changing the version numbers of lzo to 2.10, the current one) but my build fails. Here is the error message:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (build-native-non-win) on project hadoop-lzo: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec failonerror="true" dir="${build.native}" executable="sh">... @ 16:66 in /home/gianluca/hadoop-lzo/target/antrun/build-build-native-non-win.xml
```

How could I fix that?

**Comment by giamic** [comment]
Sorry for spamming, I found a solution: it was a problem with the JAVA_HOME path.

**Comment by chentyler** [comment]
> Sorry for spamming, I found a solution: it was a problem with the JAVA_HOME path.
Hello,
    When I am buiding the project  to generate executable programs, I also encounter this error.
Please tell me the solution. Thank you very much.

**Comment by chentyler** [comment]
> Hello,
> I follow the build instructions (changing the version numbers of lzo to 2.10, the current one) but my build fails. Here is the error message:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (build-native-non-win) on project hadoop-lzo: An Ant BuildException has occured: exec returned: 1
> [ERROR] around Ant part ...<exec failonerror="true" dir="${build.native}" executable="sh">... @ 16:66 in /home/gianluca/hadoop-lzo/target/antrun/build-build-native-non-win.xml
> ```
> How could I fix that?
Hello,
When I am buiding the project to generate executable programs, I also encounter this error.
Please tell me the solution. Thank you very much.

**Comment by chenshuai1995** [comment]
> Sorry for spamming, I found a solution: it was a problem with the JAVA_HOME path.

Hi, i also have the same problem. But i check the JAVA_HOME and it is right. Could you tell me how to slove this problem?

**Comment by nishantKumarGaian** [comment]
Did anyone find solution to this problem ?

**Comment by nishantKumarGaian** [comment]
> > Sorry for spamming, I found a solution: it was a problem with the JAVA_HOME path.
> 
> Hi, i also have the same problem. But i check the JAVA_HOME and it is right. Could you tell me how to slove this problem?

Did anyone find solution to this issue ?

**Comment by chenshuai1995** [comment]
Hi, i had check the JAVA_HOME path. There is no problem about the JAVA_HOME path. Can you explain in detail?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "twitter/hadoop-lzo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [twitter/hadoop-lzo] Build Failure on Ubuntu (#135)





   
Sorry for spamming, I found a solution: it was a problem with the JAVA_HOME path.
  
Hi, i also have the same problem. But i check the JAVA_HOME and it is right. Could you tell me how to slove this problem?
  
Did anyone find solution to this issue ?
