### ISSUE TITLE
Build fails on ubuntu 12.04

### ISSUE THREAD

**Issue by petercogan** [twitter/hadoop-lzo#55]
Hi, 

I have a problem that looks very similar to issue 33. It seems that HADOOP_LZO_LIBRARY is not being set correctly. 

My system is as follows: ant 1.8.2, java 1.6.0_24

I've tried gcc 4.6 and 4.4 with same results

The compilation output error is as follows:

 [exec] 	/bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/home/peter/compiled/twitter-hadoop-lzo-cc0cdbd/src/native -I./impl  -I/usr/lib/jvm/java-6-openjdk-amd64/include -I/usr/lib/jvm/java-6-openjdk-amd64/include/linux -I/home/peter/compiled/twitter-hadoop-lzo-cc0cdbd/src/native/impl -Is/home/peter/compiled/twitter-hadoop-lzo-cc0cdbd/src/native/impl/lzo/LzoCompressor.c: In function ‘Java_com_hadoop_compression_rc/com/hadoop/compression/lzo  -g -Wall -fPIC -O2 -m64 -g -O2 -MT impl/lzo/LzoCompressor.lo -MD -MP -MF $depbase.Tpo -c -o impl/lzo_LzoCompressor_initIDs’:
     [exec] /home/peter/compiled/twitter-hadoop-lzo-cc0cdbd/src/native/impl/lzo/LzoCompressor.c:125:37: error: expected expression before ‘,’ token

Note that in issue 33, one fix is to set the following flag:

LDFLAGS="-Wl,--no-as-needed"

however that does not seem to work for me. 

thanks
Peter

**Comment by sjlee** [comment]
Against a recent version of ubuntu, I can follow the instructions of installing lzo and building hadoop-lzo with maven fine. Closing.
