### ISSUE TITLE
Embed the native libraries in the hadoop-lzo jar

### ISSUE THREAD

**Issue by julienledem** [twitter/hadoop-lzo#73]
the snappy-java library has this cool feature of embedding the native libraries in the jar and loads the correct one depending on the os. That would be a cool feature to add to LZO and would make testing easier.
https://github.com/xerial/snappy-java

in particular:
https://github.com/xerial/snappy-java/blob/develop/src/main/java/org/xerial/snappy/SnappyLoader.java
https://github.com/xerial/snappy-java/tree/develop/src/main/resources/org/xerial/snappy/native

**Comment by zman0900** [comment]
Sorry to bring this back from the dead, but are there any plans to do a release with this?  If so, what platform will the jar in the maven repo be built for?

**Comment by sjlee** [comment]
Sorry this fell through the cracks. I was hoping to close PR #90 before cutting a release, but that's stalled. I could do a release before that as it's been some time.

My baseline thinking is to have x86_64 built into the jar for the maven central as that would probably be the largest user base. Thoughts?

**Comment by zman0900** [comment]
We are running on x86_64 Linux here, so that would be perfect for me.

**Comment by zman0900** [comment]
Any news on that release?  If you do decide to release, any chance PR #117 could be included?

**Comment by sjlee** [comment]
My apologies things got delayed a while. Hopefully I can pick this up next week. Yes, I'll look at #117 before a release. Thanks for your patience.

**Comment by harperjiang** [comment]
I realize this is a pretty old post. But may I know the current situation?

**Comment by sjlee** [comment]
AFAIK, the 0.4.20 release has this: https://github.com/twitter/hadoop-lzo/releases/tag/release-0.4.20
